version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php-fpm:fpmservice"
    volumes:
      - ./www:/www

  php-fpm:
    build: ./php-fpm
    ports:
      - "9000:9000"
    links:
      - "mysql"
    volumes:
      - ./www:/www

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./www/mysql/:/var/lib/mysql

