FROM nginx
MAINTAINER  <chubo.he@hand-china.com>

# The configuration for nginx image is quite simple,
# a nginx.conf is enough.
# RUN  mkdir /opt/htdocs && mkdir /opt/log && mkdir /opt/log/nginx
# RUN  chown -R www-data.www-data /opt/htdocs /opt/log
COPY nginx.conf /etc/nginx/nginx.conf
